# Generated by Django 4.2.2 on 2023-06-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sp_email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'speaker',
            },
        ),
    ]
